# 1. Introduction
Introduction of Module 2 -  **Artificial Neural Networks**

### Motivation behind Neural Networks
Human Brain is good at image recognition or pattern recognition because it has neurons in it which performs pattern
matching through input data. And there are no pre defined rules, *In the same way* Neural Networks works without pre defined rules. 

### Perceptron

The perceptron is a simple algorithm which can be used for Deep Learning. It is a type of linear classifier, i.e. a classification algorithm that makes its predictions based on a linear predictor function combining a set of weights with the feature vector. It is also known as **Artificial Neuron**. It produces a binary output. It requires input layers and weights assigned to each condition to produce an output. Input Layer - Hidden Layers - Output Layer

### Activation Functions

-> We can remove binary restrictions on a perceptron i.e instead of black or white, we can classify as dark black or black or grey black or grey or light grey or white etc. 

-> Standard Equation :
    here b refers to bias
        y = 1 if wixi + wjxj + b > 0
        y = 0 if wixi + wjxj + b <= 0  

-> Graphical Representation : It has a Step Activation Function i.e O and then direct 1.

-> Sigmoid Activation Function : also known as logistic function. Value of its output lies between 0 and 1, any real number.
    
here b refers to bias
        
    y = 1 if 1/(1+e^-(wixi + wjxj + b)) > 0.5
        
    y = 0 if 1/(1+e^-(wixi + wjxj + b)) <= 0.5

Artificial Neuron with sigmoid activation is called sigmoid neuron or logistic neuron.




### Creating Perceptron in Python

In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
iris 

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
# X = iris.data[:,:]
X = iris.data[:, (2,3)]

Categories : 

`O` : **Setosa**

`1` : **Versicolor**

`2` : **Virginica**

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
#Checking for Target 0
y = (iris.target == 0)
y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [7]:
y_categorical = y.astype(np.int)

In [8]:
y_categorical

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
print(X)


[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

In [10]:
from sklearn.linear_model import Perceptron

In [11]:
model = Perceptron(random_state=42)
model.fit(X, y_categorical)

Perceptron(random_state=42)

In [12]:
y_pred = model.predict(X)
print(y_pred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]


In [13]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
print(accuracy_score(y_categorical, y_pred))
print(confusion_matrix(y_categorical, y_pred))

1.0
[[100   0]
 [  0  50]]


In [14]:
model.coef_

array([[-1.4, -2.2]])

In [15]:
model.intercept_

array([4.])

# 2. Neural Networks - Stacking Cells to create network

### Basic Terminologies

Two ways of stacking cells: Parallel and Sequential.

Parallel: **We can get multiple outputs with same input.**
    
- Cells are executed in parallel.
    
- Cells can be executed in any order
    
- Cells can be executed multiple times

Sequential: **We get one set of putput which is input to next sequence**
    
- Cells are executed in sequential
    
- Cells can be executed only in order
    
- Cells can be executed only once

Nomenclature: 5 3 4 1 network
    
- 5 input nodes
        
- 3 hidden layer 1 nodes
        
- 4 hidden layer 2 nodes
        
- 1 output node

Input Layer -> Hidden Layer 1 -> Hidden Layer 2 -> Output Layer

*Feed Forward network i.e one directional processing*

*Fully Connected network i.e output from neuron goes to all neurons of next layer*

### Gradient Descent
- Gradient descent is an optimization algorithm or technique 
- It is used to find minimum of a function or we can it minimizes some function by iteratively moving in the direction of steepest descent as defined by the negative of the gradient
- Better than techniques such as OLS when have large no. of features and complex relationships.

- Process:
    - Assign random Weights and Biases values. (Initialization)
    - Calculate the output using these values (Forward Propagation)
    - Calculate the error using error function. (Backward Propagation)
    - Find W and B which can reduce the error.
    - Update W and B and repeat from point 2 until error is minimum. (Gradient Descent Implementation)

- Basically in short we start at random point and find out instantaneous slope at the point is GRADIENT and slightly moving in direction to steepest slope is DESCENT and then we reiterate.

- Eg: Assume predicted = 0.3 and actual = 0 then distance = 0-0.3 = -0.3
    
    \- Let error function be |-0.3| = 0.3 or (-0.3)^2 = 0.09
    
- One commonly used Error Function is Cross Entropy Error Function, it's a measure of how far away our prediction was to the correct answer.
    - Error Function:
        - Equation of Error = E = -ylog(y') - (1-y)log(1-y')
        - y = actual value
        - y' = predicted value
        - E = error
    - This function doesnot have local minimas.

    
### Back Propagation
- Back Propagation is a technique used to train a neural network.
- w = w - alpha* *del* w
- b = b - alpha* *del* b
- alpha = learning rate

- It is an algo of ANN using gradient descent. Given an ANN with E, the method calculates gradient of error function w.r.t Neural network's weights.




### Activation Function
- To put boundary conditions on output 
- To convert linear to non-linear
- Different types of Activation Functions.
    - Step Function (for classification and used at  output layer mostly)
    - Sigmoid Function (upper boundary 1 and lower zero) (used at hidden and output layers and for classificiation)
    - Tanh Function (better convergence rate than sigmoid function as it has lower boundary as -1) (same as sigmoid for layers)
    - ReLU Function (commonly used in hidden layeers and full form is Recitfied Linear Unit, till zero output is zero then output behaves like input) (Can be used for both regression and classification)

- Hidden Layers and Output Layer can have different activation functions.

- Binary Class Classification: When we have two classes yes or no 
- MultiClass classification: When we have more than 2 output classes like instead of 0 or 1 we have good better best.
    - Softmax Function:
        - It is used at output layer for multi class classification.
        - It is a generalization of sigmoid function.
        - For each class we keep one output neuron with sigmoid activation
        - We sum all the outputs from hidden layers and pass it through softmax function which gives us probability of each class.

- Important differences
    - Stochastic : single training record, forwarf and backward propagation.
    - GD : full training set, forward and backward propagation
    - Batch : All training records, forward and backward propagation.
    - Mini Batch : Small batch of training records, forward and backward propagation.
    - Epoch : One forward and backward propagation for all training records. It is one cycle though the full training data. It is different from iteration.
    - Iteration : One forward and backward propagation for one batch of training records. 
        - Eg: having 1000 training records, if we are doing stochastis then 1000 iterations within 1 epoch and if we enter 1000 records 2 time then epoch is 2.


### Loss Function
- It is used to calculate the error in the output layer.
- It is used to calculate the gradient descent.
- MSE i.e Mean Squared Error is one type of example

### Hyper Parameters
- Variable values that we set before training the model are called Hyperparameters.
- Eg: Number of hidden layers, number of neurons in each hidden layer, learning rate, number of epochs, batch size, activation function, loss function, optimizer, etc.
- Learning Rate : How fast our weights will be updated during backpropagation.
- Epochs : How many times we want to train our model on the same data.
- Batch Size : How many training records we want to use in one iteration.

- No. of input neurons = no. of features of the dataset.
- No. of output neurons = no. of classes in the dataset.
- No. of hidden layers = 1 to 5. generally 2 is a good value.
- One common structure: If we have 3 hidden layers then neurons in 1st hidden layer 300 then in 2nd 200 and in 3rd 100, pyramic like structure.
- Generally for regression problems we don't use activation function at output layer.
- Generally for classification problems we use softmax function at output layer.
- Generally for hidden layers we use ReLU function.
- Generally for regression problems we use MSE as loss function.
- Generally for classification problems we use cross entropy as loss function.
- Generally for regression problems we use Stochastic GD as optimizer.
- Generally for classification problems we use Adam as optimizer.
- Generally for regression problems we use 1 hidden layer.
- Generally for classification problems we use 2 hidden layers.
- Generally for regression problems we use 1 neuron in output layer.
- Generally for classification problems we use n neurons in output layer where n is the number of classes.
